### ISSUE TITLE
Cloudflare block

### ISSUE THREAD

**Issue by nopeless** [Cazka/diepsocket#7]
It seems that the method to get the link does not work any more due to the link being changed to `https://api-game.rivet.gg/v1/matchmaker/lobbies/find`

I wanted to fix it myself but I was blocked by cloudflare and I don't have enough knowledge to fix it. Can you help?

**Comment by Cazka** [comment]
Do not try to fix it. You will get stuck at unshuffling the packets.

**Comment by Cazka** [comment]
You can find information about unshuffling here https://github.com/ABCxFF/diepindepth/blob/main/protocol/crypto.md

**Comment by nopeless** [comment]
Well, thanks for warning me

I should maybe go for something different like  PIL as an even higher interface. 

👍

**Comment by Cazka** [comment]
Or you can checkout https://github.com/Cazka/diepAPI

**Comment by nopeless** [comment]
thanks 👍
